apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webappone
  namespace: argocd
spec:
  destination:
    namespace: webappone
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/wkk1020/Argo-CD-for-the-Absolute-Beginners.git
    path: Section13_Declarative_Demo/apps/webappone
    targetRevision: HEAD
