apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapptwo
  namespace: argocd
spec:
  destination:
    namespace: webapptwo
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/wkk1020/Argo-CD-for-the-Absolute-Beginners.git
    path: Section13_Declarative_Demo/apps/webapptwo
    targetRevision: HEAD
